### ISSUE TITLE
Unable to run example scripts in playground. 

### ISSUE THREAD

**Issue by EigenSolver** [EvoEvolver/EvoNote#18]
### Bug Description

I try to execute the files in playground. Yet, it doesn't work. 

Execute `notebook_to_paragraph.py`

```
/Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/venv/bin/python /Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/playground/notebook_to_paragraph.py playground 
  warnings.warn(
Traceback (most recent call last):
  File "/Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/playground/notebook_to_paragraph.py", line 8, in <module>
    notetree = Tree.load("AI4Science.enb")
  File "/Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/evonote/notetree/tree.py", line 312, in load
    notetree = dill.load(f)
  File "/Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/venv/lib/python3.9/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/venv/lib/python3.9/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
  File "/Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/venv/lib/python3.9/site-packages/dill/_dill.py", line 432, in find_class
    return StockUnpickler.find_class(self, module, name)
ModuleNotFoundError: No module named 'evonote.notebook.notebook'
No keys to show

Process finished with exit code 1
```

Execute `analyse_the_project.py`
```
/Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/venv/bin/python /Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/playground/analyze_project.py playground 
Traceback (most recent call last):
  File "/Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/playground/analyze_project.py", line 3, in <module>
    from evonote.transform.module_to_notetree import get_notetree_for_module
  File "/Users/yuning/Library/CloudStorage/OneDrive-Personal/EvoNote/evonote/transform/module_to_notetree.py", line 54
    match child_struct.struct_type:
          ^
SyntaxError: invalid syntax

Process finished with exit code 1
```

### Steps to Reproduce

Execute the playground files in PyCharm.  

### LLM Base

GPT3.5

### Python Version

3.9.6

### Operating System

macOS 14.0

**Comment by doomspec** [comment]
fixed in 24c35ba
